install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("raster")
install.packages("sp")
install.packages("devtools")
devtools::install_github("ncsu-landscape-dynamics/rpops", ref = "v1.0.2")